import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineClock,
  HiCheck,
  HiArrowUp,
  HiOutlineLockClosed,
  HiOutlineArrowPath,
  HiOutlineBriefcase,
  HiOutlineAcademicCap,
  HiOutlineCodeBracket,
  HiOutlineSparkles,
  HiChevronRight,
  HiChevronLeft,
  HiChevronDown,
  HiChevronUp,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import { SiJavascript, SiNextdotjs, SiFigma, SiSupabase } from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  instagram: FaInstagram,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  clock: HiOutlineClock,
  check: HiCheck,
  arrowUp: HiArrowUp,
  lock: HiOutlineLockClosed,
  refresh: HiOutlineArrowPath,
  briefcase: HiOutlineBriefcase,
  academic: HiOutlineAcademicCap,
  codeBracket: HiOutlineCodeBracket,
  sparkles: HiOutlineSparkles,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  chevronDown: HiChevronDown,
  chevronUp: HiChevronUp,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
